spring:
  application:
    name: pharma-order-service  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartpharma_db?searchpath=oms_schema
    username: postgres
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect        
    show-sql: true 
server:
  port: 8082
  servlet:
    context-path: /pharma
app:
  config:
    aws:
      region: ap-south-1
      access-key-id: AKIAWON4OXQ7GLTRXJQV
      secret-key-id: 2oFUlSxPOM2tiPuGM4Vrpa/0F+nR72DyybWzqoH/
    message:
      queue:
        topic: sample-queue
springdoc:
  api-docs:
    path: /pharma/swagger-ui.html
